config/routes.rb
Rails.application.routes.draw do

  get 'home/about'
  get 'home/contact'
  get 'home/location'
  get 'home/our_coffee'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks'
  }

  resources :farmerberries
  resources :farmers
  resources :factoryfarmberries
  resources :workers
  resources :expenditures
  resources :factoryfarms
  resources :factories
  resources :coffeberries
  resources :admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

 
    get 'dashboard', to: 'admins#dashboard'
    # get 'users', to: 'admins#users'
    # get 'posts', to: 'admins#posts'

  # post '/update_active_menu', to: 'admins#dashboard'  
  post '/update_active_menu', to: 'admins#update_active_menu'
  get '/signup_redirect' => 'factories#index'
  get '/signin_redirect' => 'factories#index'


  # Defines the root path route ("/")
   root "home#index"
end

app/models/ability.rb
# class Ability
#   include CanCan::Ability

#   def initialize(user)
#     # Define abilities for the passed in user here. For example:
#     #
#     #   user ||= User.new # guest user (not logged in)
#     #   if user.admin?
#     #     can :manage, :all
#     #   else
#     #     can :read, :all
#     #   end
#     #
#     # The first argument to `can` is the action you are giving the user
#     # permission to do.
#     # If you pass :manage it will apply to every action. Other common actions
#     # here are :read, :create, :update and :destroy.
#     #
#     # The second argument is the resource the user can perform the action on.
#     # If you pass :all it will apply to every resource. Otherwise pass a Ruby
#     # class of the resource.
#     #
#     # The third argument is an optional hash of conditions to further filter the
#     # objects.
#     # For example, here the user can only update published articles.
#     #
#     #   can :update, Article, :published => true
#     #
#     # See the wiki for details:
#     # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
#   end
# end
class Ability
  include CanCan::Ability
  def initialize(user)
    user ||= User.new
    if user.client?
      can :manage, Worker, user_id: user.id
    elsif user.admin?
      can :manage
    else
      can :read, :all
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/coffeberry.rb
class Coffeberry < ApplicationRecord
    has_many :factoryfarmberries
  has_many :farmerberries
end

app/models/expenditure.rb
class Expenditure < ApplicationRecord
  belongs_to :factory
  belongs_to :factoryfarm
end

app/models/factory.rb
class Factory < ApplicationRecord
  has_many :factoryfarms
  has_many :expenditures
  has_many :workers
end

app/models/factoryfarm.rb
class Factoryfarm < ApplicationRecord
  belongs_to :factory
  has_many :factoryfarmberries
  has_many :expenditures
end

app/models/factoryfarmberry.rb
class Factoryfarmberry < ApplicationRecord
  belongs_to :coffeberry
  belongs_to :factoryfarm
end

app/models/farmer.rb
class Farmer < ApplicationRecord
     has_many :farmerberries
end

app/models/farmerberry.rb
class Farmerberry < ApplicationRecord
  belongs_to :farmer
  belongs_to :coffeberry
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true
            #  :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  def admin?
  has_role?(:admin)
end

def client?
  has_role?(:client)
end 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/worker.rb
class Worker < ApplicationRecord
  belongs_to :factory
end

app/controllers/factories_controller.rb
class FactoriesController < ApplicationController
  before_action :set_factory, only: %i[ show edit update destroy ]

  # GET /factories or /factories.json
  def index
    @factories = Factory.all
  end

  # GET /factories/1 or /factories/1.json
  def show
  end

  # GET /factories/new
  def new
    @factory = Factory.new
  end

  # GET /factories/1/edit
  def edit
  end

  # POST /factories or /factories.json
  def create
    @factory = Factory.new(factory_params)

    respond_to do |format|
      if @factory.save
        format.html { redirect_to factory_url(@factory), notice: "Factory was successfully created." }
        format.json { render :show, status: :created, location: @factory }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @factory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /factories/1 or /factories/1.json
  def update
    respond_to do |format|
      if @factory.update(factory_params)
        format.html { redirect_to factory_url(@factory), notice: "Factory was successfully updated." }
        format.json { render :show, status: :ok, location: @factory }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @factory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /factories/1 or /factories/1.json
  def destroy
    @factory.destroy

    respond_to do |format|
      format.html { redirect_to factories_url, notice: "Factory was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_factory
      @factory = Factory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def factory_params
      params.require(:factory).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def about
  end

  def contact
  end

  def location
  end

  def our_coffee
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/factories_helper.rb
module FactoriesHelper
end

app/helpers/farmers_helper.rb
module FarmersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/factories/_factory.html.erb
<div id="<%= dom_id factory %>">
  <p>
    <strong>Name:</strong>
    <%= factory.name %>
  </p>

</div>

app/views/factories/_form.html.erb
<%= form_with(model: factory) do |form| %>
  <% if factory.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(factory.errors.count, "error") %> prohibited this factory from being saved:</h2>

      <ul>
        <% factory.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/factories/edit.html.erb
<h1>Editing factory</h1>

<%= render "form", factory: @factory %>

<br>

<div>
  <%= link_to "Show this factory", @factory %> |
  <%= link_to "Back to factories", factories_path %>
</div>

app/views/factories/index.html.erb
<h1>Factories</h1>

<% if user_signed_in? %>
  <%= button_to "logout", destroy_user_session_path, method: :delete  %>
<% else %>
  <%= link_to "Get Started", user_session_path %>
<% end %>

<div id="factories">
  <% @factories.each do |factory| %>
    <%= render factory %>
    <p>
      <%= link_to "Show this factory", factory %>
    </p>
  <% end %>
</div>

<%= link_to "New factory", new_factory_path %>

app/views/factories/new.html.erb
<h1>New factory</h1>

<%= render "form", factory: @factory %>

<br>

<div>
  <%= link_to "Back to factories", factories_path %>
</div>

app/views/factories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @factory %>

<div>
  <%= link_to "Edit this factory", edit_factory_path(@factory) %> |
  <%= link_to "Back to factories", factories_path %>

  <%= button_to "Destroy this factory", @factory, method: :delete %>
</div>