config/routes.rb
Rails.application.routes.draw do

  get 'home/about'
  get 'home/contact'
  get 'home/location'
  get 'home/our_coffee'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks'
  }

  resources :farmerberries
  resources :farmers
  resources :factoryfarmberries
  resources :workers
  resources :expenditures
  resources :factoryfarms
  resources :factories
  resources :coffeberries
  resources :admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

 
    get 'dashboard', to: 'admins#dashboard'
    # get 'users', to: 'admins#users'
    # get 'posts', to: 'admins#posts'

  # post '/update_active_menu', to: 'admins#dashboard'  
  post '/update_active_menu', to: 'admins#update_active_menu'
  get '/signup_redirect' => 'factories#index'
  get '/signin_redirect' => 'factories#index'


  # Defines the root path route ("/")
   root "home#index"
end

app/models/ability.rb
# class Ability
#   include CanCan::Ability

#   def initialize(user)
#     # Define abilities for the passed in user here. For example:
#     #
#     #   user ||= User.new # guest user (not logged in)
#     #   if user.admin?
#     #     can :manage, :all
#     #   else
#     #     can :read, :all
#     #   end
#     #
#     # The first argument to `can` is the action you are giving the user
#     # permission to do.
#     # If you pass :manage it will apply to every action. Other common actions
#     # here are :read, :create, :update and :destroy.
#     #
#     # The second argument is the resource the user can perform the action on.
#     # If you pass :all it will apply to every resource. Otherwise pass a Ruby
#     # class of the resource.
#     #
#     # The third argument is an optional hash of conditions to further filter the
#     # objects.
#     # For example, here the user can only update published articles.
#     #
#     #   can :update, Article, :published => true
#     #
#     # See the wiki for details:
#     # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
#   end
# end
class Ability
  include CanCan::Ability
  def initialize(user)
    user ||= User.new
    if user.client?
      can :manage, Worker, user_id: user.id
    elsif user.admin?
      can :manage
    else
      can :read, :all
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/coffeberry.rb
class Coffeberry < ApplicationRecord
    has_many :factoryfarmberries
  has_many :farmerberries
end

app/models/expenditure.rb
class Expenditure < ApplicationRecord
  belongs_to :factory
  belongs_to :factoryfarm
end

app/models/factory.rb
class Factory < ApplicationRecord
  has_many :factoryfarms
  has_many :expenditures
  has_many :workers
end

app/models/factoryfarm.rb
class Factoryfarm < ApplicationRecord
  belongs_to :factory
  has_many :factoryfarmberries
  has_many :expenditures
end

app/models/factoryfarmberry.rb
class Factoryfarmberry < ApplicationRecord
  belongs_to :coffeberry
  belongs_to :factoryfarm
end

app/models/farmer.rb
class Farmer < ApplicationRecord
     has_many :farmerberries
end

app/models/farmerberry.rb
class Farmerberry < ApplicationRecord
  belongs_to :farmer
  belongs_to :coffeberry
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true
            #  :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  def admin?
  has_role?(:admin)
end

def client?
  has_role?(:client)
end 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/worker.rb
class Worker < ApplicationRecord
  belongs_to :factory
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def about
  end

  def contact
  end

  def location
  end

  def our_coffee
  end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: %i[ show edit update destroy ]

  # GET /workers or /workers.json
  def index
    @workers = Worker.all
  end

  # GET /workers/1 or /workers/1.json
  def show
  end

  # GET /workers/new
  def new
    @worker = Worker.new
  end

  # GET /workers/1/edit
  def edit
  end

  # POST /workers or /workers.json
  def create
    @worker = Worker.new(worker_params)

    respond_to do |format|
      if @worker.save
        format.html { redirect_to worker_url(@worker), notice: "Worker was successfully created." }
        format.json { render :show, status: :created, location: @worker }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workers/1 or /workers/1.json
  def update
    respond_to do |format|
      if @worker.update(worker_params)
        format.html { redirect_to worker_url(@worker), notice: "Worker was successfully updated." }
        format.json { render :show, status: :ok, location: @worker }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workers/1 or /workers/1.json
  def destroy
    @worker.destroy

    respond_to do |format|
      format.html { redirect_to workers_url, notice: "Worker was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worker
      @worker = Worker.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def worker_params
      params.require(:worker).permit(:factory_id, :name, :role, :salary)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/factories_helper.rb
module FactoriesHelper
end

app/helpers/farmers_helper.rb
module FarmersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/workers/_form.html.erb
<%= form_with(model: worker) do |form| %>
  <% if worker.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(worker.errors.count, "error") %> prohibited this worker from being saved:</h2>

      <ul>
        <% worker.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :factory_id, style: "display: block" %>
    <%= form.text_field :factory_id %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :role, style: "display: block" %>
    <%= form.text_field :role %>
  </div>

  <div>
    <%= form.label :salary, style: "display: block" %>
    <%= form.number_field :salary %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/workers/_worker.html.erb
<div id="<%= dom_id worker %>">
  <p>
    <strong>Factory:</strong>
    <%= worker.factory_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= worker.name %>
  </p>

  <p>
    <strong>Role:</strong>
    <%= worker.role %>
  </p>

  <p>
    <strong>Salary:</strong>
    <%= worker.salary %>
  </p>

</div>

app/views/workers/edit.html.erb
<h1>Editing worker</h1>

<%= render "form", worker: @worker %>

<br>

<div>
  <%= link_to "Show this worker", @worker %> |
  <%= link_to "Back to workers", workers_path %>
</div>

app/views/workers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Workers</h1>

<div id="workers">
  <% @workers.each do |worker| %>
    <%= render worker %>
    <p>
      <%= link_to "Show this worker", worker %>
    </p>
  <% end %>
</div>

<%= link_to "New worker", new_worker_path %>

app/views/workers/new.html.erb
<h1>New worker</h1>

<%= render "form", worker: @worker %>

<br>

<div>
  <%= link_to "Back to workers", workers_path %>
</div>

app/views/workers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @worker %>

<div>
  <%= link_to "Edit this worker", edit_worker_path(@worker) %> |
  <%= link_to "Back to workers", workers_path %>

  <%= button_to "Destroy this worker", @worker, method: :delete %>
</div>