config/routes.rb
Rails.application.routes.draw do

  get 'home/about'
  get 'home/contact'
  get 'home/location'
  get 'home/our_coffee'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks'
  }

  resources :farmerberries
  resources :farmers
  resources :factoryfarmberries
  resources :workers
  resources :expenditures
  resources :factoryfarms
  resources :factories
  resources :coffeberries
  resources :admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

 
    get 'dashboard', to: 'admins#dashboard'
    # get 'users', to: 'admins#users'
    # get 'posts', to: 'admins#posts'

  # post '/update_active_menu', to: 'admins#dashboard'  
  post '/update_active_menu', to: 'admins#update_active_menu'
  get '/signup_redirect' => 'factories#index'
  get '/signin_redirect' => 'factories#index'


  # Defines the root path route ("/")
   root "home#index"
end

app/models/ability.rb
# class Ability
#   include CanCan::Ability

#   def initialize(user)
#     # Define abilities for the passed in user here. For example:
#     #
#     #   user ||= User.new # guest user (not logged in)
#     #   if user.admin?
#     #     can :manage, :all
#     #   else
#     #     can :read, :all
#     #   end
#     #
#     # The first argument to `can` is the action you are giving the user
#     # permission to do.
#     # If you pass :manage it will apply to every action. Other common actions
#     # here are :read, :create, :update and :destroy.
#     #
#     # The second argument is the resource the user can perform the action on.
#     # If you pass :all it will apply to every resource. Otherwise pass a Ruby
#     # class of the resource.
#     #
#     # The third argument is an optional hash of conditions to further filter the
#     # objects.
#     # For example, here the user can only update published articles.
#     #
#     #   can :update, Article, :published => true
#     #
#     # See the wiki for details:
#     # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
#   end
# end
class Ability
  include CanCan::Ability
  def initialize(user)
    user ||= User.new
    if user.client?
      can :manage, Worker, user_id: user.id
    elsif user.admin?
      can :manage
    else
      can :read, :all
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/coffeberry.rb
class Coffeberry < ApplicationRecord
    has_many :factoryfarmberries
  has_many :farmerberries
end

app/models/expenditure.rb
class Expenditure < ApplicationRecord
  belongs_to :factory
  belongs_to :factoryfarm
end

app/models/factory.rb
class Factory < ApplicationRecord
  has_many :factoryfarms
  has_many :expenditures
  has_many :workers
end

app/models/factoryfarm.rb
class Factoryfarm < ApplicationRecord
  belongs_to :factory
  has_many :factoryfarmberries
  has_many :expenditures
end

app/models/factoryfarmberry.rb
class Factoryfarmberry < ApplicationRecord
  belongs_to :coffeberry
  belongs_to :factoryfarm
end

app/models/farmer.rb
class Farmer < ApplicationRecord
     has_many :farmerberries
end

app/models/farmerberry.rb
class Farmerberry < ApplicationRecord
  belongs_to :farmer
  belongs_to :coffeberry
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true
            #  :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  def admin?
  has_role?(:admin)
end

def client?
  has_role?(:client)
end 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/worker.rb
class Worker < ApplicationRecord
  belongs_to :factory
end

app/controllers/farmerberries_controller.rb
class FarmerberriesController < ApplicationController
  before_action :set_farmerberry, only: %i[ show edit update destroy ]

  # GET /farmerberries or /farmerberries.json
  def index
    @farmerberries = Farmerberry.all
  end

  # GET /farmerberries/1 or /farmerberries/1.json
  def show
  end

  # GET /farmerberries/new
  def new
    @farmerberry = Farmerberry.new
  end

  # GET /farmerberries/1/edit
  def edit
  end

  # POST /farmerberries or /farmerberries.json
  def create
    @farmerberry = Farmerberry.new(farmerberry_params)

    respond_to do |format|
      if @farmerberry.save
        format.html { redirect_to farmerberry_url(@farmerberry), notice: "Farmerberry was successfully created." }
        format.json { render :show, status: :created, location: @farmerberry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @farmerberry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /farmerberries/1 or /farmerberries/1.json
  def update
    respond_to do |format|
      if @farmerberry.update(farmerberry_params)
        format.html { redirect_to farmerberry_url(@farmerberry), notice: "Farmerberry was successfully updated." }
        format.json { render :show, status: :ok, location: @farmerberry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @farmerberry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /farmerberries/1 or /farmerberries/1.json
  def destroy
    @farmerberry.destroy

    respond_to do |format|
      format.html { redirect_to farmerberries_url, notice: "Farmerberry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_farmerberry
      @farmerberry = Farmerberry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def farmerberry_params
      params.require(:farmerberry).permit(:season, :kg, :farmers_id, :coffeberries_id)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/factories_helper.rb
module FactoriesHelper
end

app/helpers/farmerberries_helper.rb
module FarmerberriesHelper
end

app/helpers/farmers_helper.rb
module FarmersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/farmerberries/_farmerberry.html.erb
<div id="<%= dom_id farmerberry %>">
  <p>
    <strong>Season:</strong>
    <%= farmerberry.season %>
  </p>

  <p>
    <strong>Kg:</strong>
    <%= farmerberry.kg %>
  </p>

  <p>
    <strong>Farmers:</strong>
    <%= farmerberry.farmers_id %>
  </p>

  <p>
    <strong>Coffeberries:</strong>
    <%= farmerberry.coffeberries_id %>
  </p>

</div>

app/views/farmerberries/_form.html.erb
<%= form_with(model: farmerberry) do |form| %>
  <% if farmerberry.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(farmerberry.errors.count, "error") %> prohibited this farmerberry from being saved:</h2>

      <ul>
        <% farmerberry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :season, style: "display: block" %>
    <%= form.text_field :season %>
  </div>

  <div>
    <%= form.label :kg, style: "display: block" %>
    <%= form.number_field :kg %>
  </div>

  <div>
    <%= form.label :farmers_id, style: "display: block" %>
    <%= form.text_field :farmers_id %>
  </div>

  <div>
    <%= form.label :coffeberries_id, style: "display: block" %>
    <%= form.text_field :coffeberries_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/farmerberries/edit.html.erb
<h1>Editing farmerberry</h1>

<%= render "form", farmerberry: @farmerberry %>

<br>

<div>
  <%= link_to "Show this farmerberry", @farmerberry %> |
  <%= link_to "Back to farmerberries", farmerberries_path %>
</div>

app/views/farmerberries/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Farmerberries</h1>

<div id="farmerberries">
  <% @farmerberries.each do |farmerberry| %>
    <%= render farmerberry %>
    <p>
      <%= link_to "Show this farmerberry", farmerberry %>
    </p>
  <% end %>
</div>

<%= link_to "New farmerberry", new_farmerberry_path %>

app/views/farmerberries/new.html.erb
<h1>New farmerberry</h1>

<%= render "form", farmerberry: @farmerberry %>

<br>

<div>
  <%= link_to "Back to farmerberries", farmerberries_path %>
</div>

app/views/farmerberries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @farmerberry %>

<div>
  <%= link_to "Edit this farmerberry", edit_farmerberry_path(@farmerberry) %> |
  <%= link_to "Back to farmerberries", farmerberries_path %>

  <%= button_to "Destroy this farmerberry", @farmerberry, method: :delete %>
</div>