config/routes.rb
Rails.application.routes.draw do

  get 'home/about'
  get 'home/contact'
  get 'home/location'
  get 'home/our_coffee'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks'
  }

  resources :farmerberries
  resources :farmers
  resources :factoryfarmberries
  resources :workers
  resources :expenditures
  resources :factoryfarms
  resources :factories
  resources :coffeberries
  resources :admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

 
    get 'dashboard', to: 'admins#dashboard'
    # get 'users', to: 'admins#users'
    # get 'posts', to: 'admins#posts'

  # post '/update_active_menu', to: 'admins#dashboard'  
  post '/update_active_menu', to: 'admins#update_active_menu'
  get '/signup_redirect' => 'factories#index'
  get '/signin_redirect' => 'factories#index'


  # Defines the root path route ("/")
   root "home#index"
end

app/models/ability.rb
# class Ability
#   include CanCan::Ability

#   def initialize(user)
#     # Define abilities for the passed in user here. For example:
#     #
#     #   user ||= User.new # guest user (not logged in)
#     #   if user.admin?
#     #     can :manage, :all
#     #   else
#     #     can :read, :all
#     #   end
#     #
#     # The first argument to `can` is the action you are giving the user
#     # permission to do.
#     # If you pass :manage it will apply to every action. Other common actions
#     # here are :read, :create, :update and :destroy.
#     #
#     # The second argument is the resource the user can perform the action on.
#     # If you pass :all it will apply to every resource. Otherwise pass a Ruby
#     # class of the resource.
#     #
#     # The third argument is an optional hash of conditions to further filter the
#     # objects.
#     # For example, here the user can only update published articles.
#     #
#     #   can :update, Article, :published => true
#     #
#     # See the wiki for details:
#     # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
#   end
# end
class Ability
  include CanCan::Ability
  def initialize(user)
    user ||= User.new
    if user.client?
      can :manage, Worker, user_id: user.id
    elsif user.admin?
      can :manage
    else
      can :read, :all
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/coffeberry.rb
class Coffeberry < ApplicationRecord
    has_many :factoryfarmberries
  has_many :farmerberries
end

app/models/expenditure.rb
class Expenditure < ApplicationRecord
  belongs_to :factory
  belongs_to :factoryfarm
end

app/models/factory.rb
class Factory < ApplicationRecord
  has_many :factoryfarms
  has_many :expenditures
  has_many :workers
end

app/models/factoryfarm.rb
class Factoryfarm < ApplicationRecord
  belongs_to :factory
  has_many :factoryfarmberries
  has_many :expenditures
end

app/models/factoryfarmberry.rb
class Factoryfarmberry < ApplicationRecord
  belongs_to :coffeberry
  belongs_to :factoryfarm
end

app/models/farmer.rb
class Farmer < ApplicationRecord
     has_many :farmerberries
end

app/models/farmerberry.rb
class Farmerberry < ApplicationRecord
  belongs_to :farmer
  belongs_to :coffeberry
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true
            #  :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  def admin?
  has_role?(:admin)
end

def client?
  has_role?(:client)
end 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/worker.rb
class Worker < ApplicationRecord
  belongs_to :factory
end

app/controllers/expenditures_controller.rb
class ExpendituresController < ApplicationController
  before_action :set_expenditure, only: %i[ show edit update destroy ]

  # GET /expenditures or /expenditures.json
  def index
    @expenditures = Expenditure.all
  end

  # GET /expenditures/1 or /expenditures/1.json
  def show
  end

  # GET /expenditures/new
  def new
    @expenditure = Expenditure.new
  end

  # GET /expenditures/1/edit
  def edit
  end

  # POST /expenditures or /expenditures.json
  def create
    @expenditure = Expenditure.new(expenditure_params)

    respond_to do |format|
      if @expenditure.save
        format.html { redirect_to expenditure_url(@expenditure), notice: "Expenditure was successfully created." }
        format.json { render :show, status: :created, location: @expenditure }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @expenditure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenditures/1 or /expenditures/1.json
  def update
    respond_to do |format|
      if @expenditure.update(expenditure_params)
        format.html { redirect_to expenditure_url(@expenditure), notice: "Expenditure was successfully updated." }
        format.json { render :show, status: :ok, location: @expenditure }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @expenditure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenditures/1 or /expenditures/1.json
  def destroy
    @expenditure.destroy

    respond_to do |format|
      format.html { redirect_to expenditures_url, notice: "Expenditure was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expenditure
      @expenditure = Expenditure.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def expenditure_params
      params.require(:expenditure).permit(:factory_id, :name, :status, :factoryfarms_id)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenditures_helper.rb
module ExpendituresHelper
end

app/helpers/factories_helper.rb
module FactoriesHelper
end

app/helpers/farmers_helper.rb
module FarmersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/expenditures/_expenditure.html.erb
<div id="<%= dom_id expenditure %>">
  <p>
    <strong>Factory:</strong>
    <%= expenditure.factory_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= expenditure.name %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= expenditure.status %>
  </p>

  <p>
    <strong>Factoryfarms:</strong>
    <%= expenditure.factoryfarms_id %>
  </p>

</div>

app/views/expenditures/_form.html.erb
<%= form_with(model: expenditure) do |form| %>
  <% if expenditure.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(expenditure.errors.count, "error") %> prohibited this expenditure from being saved:</h2>

      <ul>
        <% expenditure.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :factory_id, style: "display: block" %>
    <%= form.text_field :factory_id %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.label :factoryfarms_id, style: "display: block" %>
    <%= form.text_field :factoryfarms_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/expenditures/edit.html.erb
<h1>Editing expenditure</h1>

<%= render "form", expenditure: @expenditure %>

<br>

<div>
  <%= link_to "Show this expenditure", @expenditure %> |
  <%= link_to "Back to expenditures", expenditures_path %>
</div>

app/views/expenditures/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Expenditures</h1>

<div id="expenditures">
  <% @expenditures.each do |expenditure| %>
    <%= render expenditure %>
    <p>
      <%= link_to "Show this expenditure", expenditure %>
    </p>
  <% end %>
</div>

<%= link_to "New expenditure", new_expenditure_path %>

app/views/expenditures/new.html.erb
<h1>New expenditure</h1>

<%= render "form", expenditure: @expenditure %>

<br>

<div>
  <%= link_to "Back to expenditures", expenditures_path %>
</div>

app/views/expenditures/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @expenditure %>

<div>
  <%= link_to "Edit this expenditure", edit_expenditure_path(@expenditure) %> |
  <%= link_to "Back to expenditures", expenditures_path %>

  <%= button_to "Destroy this expenditure", @expenditure, method: :delete %>
</div>